options(timeout=600)
Sys.setenv(EDGAR_UA="Jozsap V9 research 35482421+Jozsap@users.noreply.github.com")
suppressPackageStartupMessages({library(data.table); library(arrow)})
setwd("RFundamentals")
source("R/constituent_master.R")
source("R/sector_classifier.R")
source("R/fundamental_fetcher.R")
source("R/indicator_compute.R")
source("R/pit_assembler.R")
source("R/pipeline_runner.R")
source("R/timeseries_builder.R")
source("R/ttm_eps.R")
dir.create("cache/lookups", recursive=TRUE, showWarnings=FALSE)
build_constituent_master()
build_sector_industry()
build_fundamentals()
build_timeseries(start_date="2014-01-02", end_date=Sys.Date())
